### ISSUE TITLE
Clean obsolete old models and organization plugin.

### ISSUE THREAD

**Issue by pdelboca** [okfn/website#1022]
The goal of the website is to be a pure CMS that coms can edit to publish information. We do not need much more than that.

However, we still have some left overs of some old database structures of Persons, Networks, Activities, Groups that looks like an Organization Management System more than a informational website. Since it is not the goal of the website to manage anything, we can move forward and remove that old structures.

This should be done after #883 is completed.

## Tasks
 - [X] First, we need to migrate all the people information to a CMS content. (Done for Team and Board)
 - [X] Remove Unit, UnitMembership, Unit urls, and AppHooks.
 - [ ] Remove Board, BoardMembersip, Board urls and AppHooks.
 - [ ] Define next steps for Network models
 - [ ] Properly implement the `SideBarExtensionToolbar` plugin (See https://github.com/okfn/website/issues/994#issuecomment-1794472231)
 - [ ] Review the feature plugin and delete it as well if it is of no use anymore
