### ISSUE TITLE
CMS plugin to display recent blog posts

### ISSUE THREAD

**Issue by nickstenning** [okfn/website#108]
Suggest this scrapes and caches blog RSS feed.

Want ability to filter by tag, author, or similar.

**Comment by macoo222** [comment]
Ano slišim to

**Comment by morchickit** [comment]
Low priority

**Comment by pwalsh** [comment]
# Tasks

- [ ] Just show latest X post from an RSS feed
- [ ] As a widget/plugin
- [ ] Use on home page ( @smth ? )

**Comment by k-nut** [comment]
I guess we could use this django-cms plugin for it : https://github.com/zgwmike/django-rss-plugin

And we want to take content from here?! http://blog.okfn.org/feed/

**Comment by pwalsh** [comment]
@k-nut great, and yes.

**Comment by k-nut** [comment]
We actually do not need to use the plugin for this as the content we want to show does not require any action by editors. It is just one feed that will always stay the same but requires special formatting. Therefore (and because using the extension turned out to break the tests) I am proposing that we just use a very simple custom extension as I provided on in https://github.com/okfn/website/commit/2f54aefb7c3b0a8f30642b979b88548ee6213829

**Comment by pwalsh** [comment]
@k-nut 👍

**Comment by k-nut** [comment]
Closing this as it is implemented in the new design.
