### ISSUE TITLE
Send in press mentions from a slack channel

### ISSUE THREAD

**Issue by nealbastek** [okfn/website#212]
We've entered a few by hand, but have a Google spreadsheet full of many more. Is it possible to import directly into the Django db?

**Comment by pwalsh** [comment]
# Tasks

- [ ] Add slack integration
- [ ] Have a dedicated Slack channel
- [ ] Each message creates a press mention in the database

(more detailed required.)

**Comment by k-nut** [comment]
If we want to use google news instead we could use this as a feed address: 
https://news.google.com/news?q=%22Open%20Knowledge%20International%22&output=rss
