### ISSUE TITLE
Set staff member statuses from slack

### ISSUE THREAD

**Issue by pwalsh** [okfn/website#292]
# Description

In the interests of being relatable, we want to make the team page more personalised.

# Tasks
 
- [x] Add a slack integration lib
- [x] Choose and setup a bot to interact in slack. Prefer some open source solution we can host on a free Heroku ( cc @morchickit @k-nut @smth )
- [x] Each of #reading #listening #location #eating #working #watching goes to a status on user, when used in the #set-public-status channel
  - [ ] So obviously we need also to associate persons with slack profiles on the oki slack
- [ ] Do something reasonable with the length of a status
- [ ] Basic tests

**Comment by smth** [comment]
The page should also have some way of knowing which of a person's statuses was most recently set. So in this example, Mor's visible status is "reading", because that  is the most recently updated (all her other statuses are available on hover/click).
![profile_02](https://cloud.githubusercontent.com/assets/1375708/16048314/7b89752a-324b-11e6-8333-36638a6de48b.jpg)

**Comment by smth** [comment]
Also, convert URLs into linked page titles?

**Comment by k-nut** [comment]
@smth like slack/facebook/etc do when you share a link?

**Comment by smth** [comment]
Exactly @k-nut so people can use Slack in a natural way (sharing a link to an article), but we can output it in a readable way (like the mock-up above).

**Comment by k-nut** [comment]
That sounds like a good idea. Most websites supply [open graph](http://ogp.me/) metadata that we can use to get the title very easily. If that is not possible we have a couple of options
- Just display the plain link
- Try to extract a heading automatically (hard and probably very likely to produce weird results)
- Just let our nice slackbot ask the user for a human readable title.

**Comment by amercader** [comment]
FYI there is an existing bot that does something similar:

http://hashtag-listener.herokuapp.com/

Source is here, maybe you can reuse some or most of it
https://github.com/okfn/hashtag-listener
